#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'database', git: 'https://github.com/opscode-cookbooks/database.git'
cookbook 'nginx'
cookbook 'openssl'
cookbook 'package_installer'
cookbook 'postgresql'
cookbook 'redis', '~> 3.0.4'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm.git'

